### ISSUE TITLE
Biểu đồ FDD, DFD, ERD

### ISSUE THREAD

**Issue by hoannguyen1352** [hoannguyen1352/CongNghePhanMem-60TH4.2-Nhom18#9]

**Comment by minhduongk82k** [comment]
Biểu đồ luồng dữ liệu (DFD)
Biểu đồ luồng dữ liệu xem tình trạng bàn còn trống cho khách








Biểu đồ luồng dữ liệu thêm khách hành vào làm hội viên 







 Biểu đồ luồng dữ liệu sửa thông tin  khách hành  hội viên 









Biểu đồ luồng dữ liệu thêm đồ uống vào bàn mà khách order 







Biểu đồ luồng dữ liệu thanh toán theo yêu cầu của khách hàng



Biểu đồ luồng dữ liệu thanh toán theo yêu cầu của khách hàng trong hội viên







Biểu đồ luồng dữ liệu thêm thông tin đồ uống vào hệ thống để cập nhật


Biểu đồ luồng dữ liệu sửa thông tin đồ uống vào hệ thống để cập nhật




Biểu đồ luồng dữ liệu xóa thông tin đồ uống vào hệ thống để

**Comment by doannguyen2000** [comment]
Biểu Đồ ERD [https://docs.google.com/document/d/1ArJRpQrp-_kL_4z3cPCZY4kQ9UGdQUlL4FeRGbl5rWg/edit?usp=sharing](url)

**Comment by Kiennguyen2312** [comment]
https://docs.google.com/document/d/1BkOD8wwHfalI1rLgQs3-dSUTeQahpaJ6ZYGfIHSbSHg/edit?usp=sharing
Biểu đồ FDD
